language: csharp
mono: none
dotnet: 3.1.201
services:
- docker
env:
  global:
  - PACT_BROKER_BASE_URL=https://footasylum.pactflow.io
  # PACT_BROKER_TOKEN is managed via the UI
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
